mod 'puppet-nginx', '1.1.0'
mod 'puppetlabs-concat', '6.2.0'
mod 'puppetlabs-stdlib', '6.3.0'
mod 'puppetlabs-translate', '2.2.0'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '3.10.0'
mod 'puppet-archive', '4.4.0'
mod 'gabe-ngrok', '1.2.1'
